name: Infra Shared Prereqs

on:
  workflow_call:
    inputs:
      terraform-rg:
        type: string
        required: true
      terraform-rg-suffix:
        type: string
        required: true
      environment:
        type: string
        required: true
        description: Target environment (e.g. dev)
      project-name:
        type: string
        required: true
      methanol-project-name:
        type: string
        required: true
      region-short:
        type: string
        required: true
      region:
        type: string
        required: true
      resource-suffix:
        type: string
        required: true
    
    secrets:
      AZURE_CREDS:
        required: true
      ARM_CLIENT_ID:
        required: true
      AD_SQL_ADMIN_OBJECT_ID:
        required: true

jobs:
  shared-prerequisites:
    name: Shared Prereqs
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
              
      - name: Azure Login
        uses: Azure/login@v1.4.3
        with:
          creds: ${{ secrets.AZURE_CREDS }}
      
      # Create resource groups
      - name: Setup prereqs
        uses: Azure/cli@v1.0.6
        with:
          inlineScript: |
            az group create -n 'RG-${{ inputs.terraform-rg-suffix }}-${{ inputs.region-short }}-${{ inputs.terraform-rg }}-${{ inputs.resource-suffix }}' -l '${{ inputs.region }}'
            az storage account create -n 'pivey${{ inputs.environment }}${{ inputs.region-short }}terraform${{ inputs.resource-suffix }}' -g 'RG-${{ inputs.terraform-rg-suffix }}-${{ inputs.region-short }}-${{ inputs.terraform-rg }}-${{ inputs.resource-suffix }}' -l '${{ inputs.region }}' --sku 'Standard_LRS'
            az storage container create -n 'terraform' --account-name 'pivey${{ inputs.environment }}${{ inputs.region-short }}terraform${{ inputs.resource-suffix }}' --auth-mode login
            az group create -n 'RG-${{ inputs.terraform-rg-suffix }}-${{ inputs.region-short }}-${{ inputs.methanol-project-name }}-${{ inputs.resource-suffix }}' -l '${{ inputs.region }}'
            az group create -n 'RG-${{ inputs.terraform-rg-suffix }}-${{ inputs.region-short }}-${{ inputs.project-name }}-${{ inputs.resource-suffix }}' -l '${{ inputs.region }}'
            az keyvault create -n 'kv-${{ inputs.environment }}-${{ inputs.region-short }}-${{ inputs.methanol-project-name }}-${{ inputs.resource-suffix }}' -l '${{ inputs.region }}' -g 'RG-${{ inputs.terraform-rg-suffix }}-${{ inputs.region-short }}-${{ inputs.methanol-project-name }}-${{ inputs.resource-suffix }}'
            az keyvault set-policy -n 'kv-${{ inputs.environment }}-${{ inputs.region-short }}-${{ inputs.methanol-project-name }}-${{ inputs.resource-suffix }}' --key-permissions 'all' --secret-permissions 'all' --spn '${{ secrets.ARM_CLIENT_ID }}'
            az keyvault set-policy -n 'kv-${{ inputs.environment }}-${{ inputs.region-short }}-${{ inputs.methanol-project-name }}-${{ inputs.resource-suffix }}' --key-permissions 'all' --secret-permissions 'all' --object-id '${{ AD_SQL_ADMIN_OBJECT_ID }}'
            
     # Logout
      - name: Az logout
        uses: Azure/cli@v1.0.6
        with:
          inlineScript: az logout