name: Reusable workflow

on:
  workflow_call:
    inputs:
      terraform-rg:
        type: string
        required: true
      terraform-rg-suffix:
        type: string
        required: true
      environment:
        type: string
        required: true
        description: Target environment (e.g. dev)
      project-name:
        type: string
        required: true
      methanol-project-name:
        type: string
        required: true
      region-short:
        type: string
        required: true
      is-dr:
        type: boolean
        required: true
        default: false
      region:
        type: string
        required: true
      resource-suffix:
        type: string
        required: true
      sql-sku-name:
        type: string
        required: true
      storage-account-replication:
        type: string
        required: true
    
    secrets:
      AZURE_CREDS:
        required: true
      ARM_CLIENT_ID:
        required: true
      ARM_TENANT_ID:
        required: true
      ARM_CLIENT_SECRET:
        required: true
      ARM_SUBSCRIPTION_ID:
        required: true
      AD_SQL_ADMIN_NAME:
        required: true
      AD_SQL_ADMIN_OBJECT_ID:
        required: true
      SQL_SERVER_ADMIN_PASSWORD:
        required: true

env:
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}      #It's specific to DEV. So need to replace it with appropriate value for each environment.
  ARM_CLIENT_SECRET: ${{secrets.ARM_CLIENT_SECRET}}  #It's specific to DEV. So need to replace it with appropriate value for each environment.
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
  Terraform-RG-SUFFIX: ${{ inputs.terraform-rg-suffix }}
  Terraform-RG: ${{ inputs.terraform-rg }}

jobs:
  shared:
    name: Provision shared infra
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    defaults:
      run:
        working-directory: Terraform/Methanol/Shared
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
              
      - name: Azure Login
        uses: Azure/login@v1.4.3
        with:
          creds: ${{ secrets.AZURE_CREDS }}
      
      # Create resource groups
      - name: Setup backend
        uses: Azure/cli@v1.0.6
        with:
          inlineScript: |
            az group create -n 'RG-${{ inputs.terraform-rg-suffix }}-${{ inputs.region-short }}-${{ inputs.terraform-rg }}-${{ inputs.resource-suffix }}' -l '${{ inputs.region }}'
            az storage account create -n 'pivey${{ inputs.environment }}${{ inputs.region-short }}terraform${{ inputs.resource-suffix }}' -g 'RG-${{ inputs.terraform-rg-suffix }}-${{ inputs.region-short }}-${{ inputs.terraform-rg }}-${{ inputs.resource-suffix }}' -l '${{ inputs.region }}' --sku 'Standard_LRS'
            az storage container create -n 'terraform' --account-name 'pivey${{ inputs.environment }}${{ inputs.region-short }}terraform${{ inputs.resource-suffix }}' --auth-mode login

#            az keyvault create -n 'kv-dev-eu-pocmthnl-001' -l '${{ inputs.region }}' -g 'RG-${{ inputs.terraform-rg-suffix }}-${{ inputs.region-short }}-${{ inputs.methanol-project-name }}-${{ inputs.resource-suffix }}' --enabled-for-template-deployment true
#            az keyvault set-policy -n 'kv-dev-eu-pocmthnl-001' --key-permissions get list update create --secret-permissions get list set --object-id '${{ secrets.ARM_CLIENT_ID }}'
      
      - uses: cschleiden/replace-tokens@v1
        name: Set up Terraform vars
        with:
          files: '["**/*.tf*"]' # TODO: Be more explicit in the files, rather than using wildcards
        env:
          Environment-Name: ${{ inputs.environment }}
          Environment-Name-Suffix: ${{ inputs.environment }}
          Environment-Name-Suffix-Short: ${{ inputs.environment }}
          Project-Name: ${{ inputs.project-name }}
          Methanol-Project-Name: ${{ inputs.methanol-project-name }}
          Region-Short: ${{ inputs.region-short }}
          Is-DR: ${{ inputs.is-dr }}
          Region: ${{ inputs.region }}
          ActiveDirectory-Tenant-Id: ${{ secrets.ARM_TENANT_ID }}
          Resource-Suffix: ${{ inputs.resource-suffix }}
          AD_SQL_ADMIN_NAME: ${{ secrets.AD_SQL_ADMIN_NAME }}
          AD_SQL_ADMIN_OBJECT_ID: ${{ secrets.AD_SQL_ADMIN_OBJECT_ID }}
          SQL_SERVER_ADMIN_PASSWORD: ${{secrets.SQL_SERVER_ADMIN_PASSWORD}}
          SQL_SKU_NAME: ${{ inputs.sql-sku-name }}
          Storage-Account-Replication: ${{ inputs.storage-account-replication }}
          
      - uses: hashicorp/setup-terraform@v1
        name: Setup Terraform
        with:
          terraform_version: 0.15.4
          terraform_wrapper: false

      - run: terraform init
        name: Terraform Init

      # Removing this for now
      #- run: terraform fmt -check
      #  name: Terraform Format

      - run: terraform plan -out=tfplan.bin --var-file=variables.tfvars -input=false
        name: Terraform Plan

      - run: terraform apply --auto-approve 'tfplan.bin'
        name: Terraform Apply
