name: Reusable workflow

on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true
        description: Target environment (e.g. dev)
      project-name:
        type: string
        required: true
      methanol-project-name:
        type: string
        required: true
      region-short:
        type: string
        required: true
      is-dr:
        type: boolean
        required: true
        default: false
      region:
        type: string
        required: true
      resource-suffix:
        type: string
        required: true
      sql-sku-name:
        type: string
        required: true
      storage-account-replication:
        type: string
        required: true
    
    secrets:
      ARM_TENANT_ID:
        required: true
      AD_SQL_ADMIN_NAME:
        required: true
      AD_SQL_ADMIN_OBJECT_ID:
        required: true
      SQL_SERVER_ADMIN_PASSWORD:
        required: true
          
jobs:
  shared:
    name: Provision shared infra
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    defaults:
      run:
        working-directory: Terraform/Methanol/Shared
    
    steps:
      - uses: actions/checkout@v2
        name: Checkout repo
      
      - uses: cschleiden/replace-tokens@v1
        name: Set up Terraform vars
        with:
          files: '["**/*.tf*"]'
        env:  #Below environment variables will be used in terraform scripts. So changing them will update the azure resource.
          Environment-Name: ${{ inputs.environment }}
          Environment-Name-Suffix: ${{ inputs.environment }}
          Environment-Name-Suffix-Short: ${{ inputs.environment }}
          Project-Name: ${{ inputs.project-name }}
          Methanol-Project-Name: ${{ inputs.methanol-project-name }}
          Region-Short: ${{ inputs.region-short }}
          Is-DR: ${{ inputs.is-dr }}
          Region: ${{ inputs.region }}
          ActiveDirectory-Tenant-Id: ${{ secrets.ARM_TENANT_ID }}
          Resource-Suffix: ${{ inputs.resource-suffix }}
          AD_SQL_ADMIN_NAME: ${{ secrets.AD_SQL_ADMIN_NAME }}
          AD_SQL_ADMIN_OBJECT_ID: ${{ secrets.AD_SQL_ADMIN_OBJECT_ID }}
          SQL_SERVER_ADMIN_PASSWORD: ${{secrets.SQL_SERVER_ADMIN_PASSWORD}}
          SQL_SKU_NAME: ${{ inputs.sql-sku-name }}
          Storage-Account-Replication: ${{ inputs.storage-account-replication }}
          
      - uses: hashicorp/setup-terraform@v1
        name: Setup Terraform
        with:
          terraform_version: 0.15.4
          terraform_wrapper: false

      - run: terraform init
        name: Terraform Init

      - run: terraform fmt -check
        name: Terraform Format

      - run: terraform plan -out=tfplan.bin --var-file=variables.tfvars -input=false
        name: Terraform Plan

      - run: terraform apply --auto-approve 'tfplan.bin'
        name: Terraform Apply
