name: Reusable workflow

on:
  workflow_call:
    inputs:
      Terraform-RG-SUFFIX:
        type: string
        required: true
          
jobs:

  reused-job:
    name: Reused job
    runs-on: ubuntu-latest
    steps:
    - run: echo Hello, World!
