name: '01_Storage'

on:
  workflow_dispatch:
    inputs:
      location:
        required: true
        type: text

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ inputs.location }}
