name: Testing

on:
  workflow_call:
    secrets:
      TEST:
        required: true
          
jobs:

  reused-job-test:
    name: Reused job (test)
    environment: test
    runs-on: ubuntu-latest
    steps:
    - run: echo ${{ secrets.TEST }}

  reused-job-test2:
    name: Reused job (test2)
    environment: test2
    runs-on: ubuntu-latest
    steps:
    - run: echo ${{ secrets.TEST }}
