name: Testing

on:
  workflow_call:
    secrets:
      TEST:
        required: true
          
jobs:

  reused-job:
    name: Reused job
    environment: test
    runs-on: ubuntu-latest
    steps:
    - run: echo ${{ secrets.TEST }}
